# Basic
title: Doris
subtitle: 『把时间当做朋友』
welcome_message: 嗨，我是芹菜，欢迎来到我的个人日志~
description: 研究领域：深度学习 图像处理
creator: <a href="http://liushiqin.com">@Doris</a>

url: "http://liushiqin.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog
   
 
# Navigation buttons in the front page.
nav:
    - {title: 主页, description: Home, url: 'http://liushiqin.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: onevcat
    phone: 127916
    mail: 374498900@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
